### ISSUE TITLE
readme guide for installation

### ISSUE THREAD

**Issue by poorprogrammer1** [lucienshawls/Free-Cloud-Compute#19]
Is it possible for you to create a detailed guide :(  ?
I am new to n2n and get stuck everywhere. 
when i run rdp in windows, it gives me error that this ip <172.16.40.122> does not exist

C:\N2N Edge GUI>edge.exe -c <some_random_community_Name> -l <N2N_ip_that_i_set_at_run_workflow>:<windows_rdp_port_at_run_workflow> -a <my computer ipv4 from ipconfig> -k <a secret keypass> -A3
31/Jul/2022 22:05:47 [     edge.c:1958] Starting n2n edge 2.0.0 Mar 25 2010 08:27:29
Adding supernode[0] = 172.16.40.122:13383
supernode 0 => 172.16.40.122:13383
supernode 1 =>
31/Jul/2022 22:05:47 [     edge.c:2225] ip_mode='static'
No Windows tap device found!

**Comment by lucienshawls** [comment]
First of all, a supernode runs on a server with a public ip address so that it is accessible to all. Computers that do not have public ip addresses can connect to that public supernode and a virtual intranet is constucted. It is as if those computers have connected to the same router and can access each other.

The instance created by GitHub Actions do not possess a public ip address, neither does your computer under most circumstances. The instance and your computer have to connect to the same supernode before they can access each other.

You need to do the following preparations:
1. Set up a supernode on a paid cloud service provider yourself or find a public one. **The host of the supernode is NOT the ip address set at workflows runs (like current default 172.16.40.122: this is not a public address).** 
2. Create GitHub Actions secrets as the README tells you, including the supernode host and port, a community name and a key for encryption. 
3. Launch the instance through GitHub Actions with an ip address. The N2N edge will configure itself and launch automatically.
4. Install a tap device on your own computer. **It seems that you missed this step.**
5. Launch the N2N edge on your own computer with the same supernode host and port, same community name and same key, but a different ip address. **It seems you assigned the same ip address, this would cause ip collisons.**

**Comment by lucienshawls** [comment]
Maybe I will add the support of some famous Intranet penetration services like ngrok. This may simplify the process.
I myself use N2N and FRP simply because I have a public server that runs a supernode and frps, but maybe they are not suitable for the public.

**Comment by lucienshawls** [comment]
Thanks for the issue, I will refine the README file.

**Comment by lucienshawls** [comment]
README file has been refined. Please open another issue if there is something unclear.
